apiVersion: v1
kind: Pod
metadata:
  name: pvc-example
spec:
  containers:
  - name: app-container
    image: busybox
    command: ["sh", "-c", "echo 'Persistent data' > /data/persistent.txt; sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: persistent-storage
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: demo-pvc

