apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: ZGJ1c2Vy  # base64 encoded "dbuser"
  password: ZGJwYXNzMTIz  # base64 encoded "dbpass123"
  rootpassword: ZGJwYXNzMTIz
